services:
  users-postgres:
    container_name: users-postgres
    restart: always
    build:
      context: docker/postgres
      dockerfile: postgres.Dockerfile
      shm_size: '256m'
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      TZ: "Asia/Novosibirsk"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 5s
    ports:
      - ${PG_EXTERNAL_PORT:-5432}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - subtrack-net
  redis:
    container_name: users-redis
    restart: always
    build:
      context: docker/redis
      dockerfile: redis.Dockerfile
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    image: redis:latest
    ports:
      - ${REDIS_EXTERNAL_PORT:-6379}:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USERNAME: ${REDIS_USERNAME}
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--requirepass", "password" ]
    networks:
      - subtrack-net
  app:
    container_name: users-app
    restart: always
    build:
      context: .
      dockerfile: docker/go-users/go.Dockerfile
      args:
        PORT: ${PUBLIC_HTTP_ADDR}
    image: users-app:latest
    environment:
      - TZ=Asia/Novosibirsk
    ports:
      - ${PUBLIC_HTTP_ADDR}:${PUBLIC_HTTP_ADDR}
    networks:
      - subtrack-net
  outbox:
    container_name: outbox
    restart: always
    build:
      context: .
      dockerfile: docker/go-outbox/go.Dockerfile
    image: outbox-app:latest
    environment:
      - TZ=Asia/Novosibirsk
    networks:
      - subtrack-net
volumes:
  pg_data:
    name: users-pg_data
  redis_data:
    name: users-redis_data
networks:
  subtrack-net:
    name: subtrack-net
    driver: bridge